### ISSUE TITLE
Start & End dates not automatically added anymore

### ISSUE THREAD

**Issue by Moonchildish** [AniLibApp/AniLib#110]
## Device Information

- **Device:** Oneplus Nord
- **Android Version:** Android 11
- **App Version:** 2.0.2-44

## Description

Does not save start and end dates correctly/automatically. 
Whenever I start something it will not set to a start date automatically. And when I manually add it it will get removed from list editior after I increment chapter/episode count once. 
Also, whenever finishing an anime/manga it won't automatically add the end date anymore.. 

## Steps to Reproduce (if applicable)

1. Go to 'List Editor' 
2. Add a start date
3. Click 'Filter' (why is that the button to save the date setting and not something like: 'save'?) 
4. Save list editor 
5. Go to 'reading' 
6. Increment chapter count once with '+' 
7. Go back to 'list editor' 
8. There is no start date anymore

## Screenshots (if applicable)

https://github.com/user-attachments/assets/bcf0fe66-d224-4fc9-83db-35d0cbcfa496

## Additional Context

Again, it also doesn't automatically add end dates anymore, which is a pain. 
It would be great if, whenever you finish a manga/anime, there's a pop up that asks you if you finished it and to add a score/notes etc. 
(This is what Android did and what the MAL Client app is doing). So might be an idea? 
---

**Comment by rev0lgenX** [comment]
Added new issue to support pop up that asks you if you finished it and to add a score/notes etc.  #111

**Comment by rev0lgenX** [comment]
@Moonchildish Can you provide a screen recording about popup from MAL?

**Comment by Moonchildish** [comment]
https://github.com/user-attachments/assets/29ad68b6-543a-477e-a948-d943c3c1ec53

![Screenshot_20241117-231438](https://github.com/user-attachments/assets/d1175a7f-6fb6-4d40-b9e0-7f7dbbbe812e)

So when I click 'yes' on the popup it will automatically set to completed and set the date to when I clicked on it. And it will ask me to score after.

**Comment by Moonchildish** [comment]
Everytime I increment with +1 it will remove the start date for some weird reason. It messes up my activity log too, super annoying

**Comment by rev0lgenX** [comment]
@Moonchildish I have pushed changes related to the issue in playstore. Please check it out.
Regards!

**Comment by Moonchildish** [comment]
That's great, thanks for the quick fixes! Really appreciate it!

One last thing:
With longer titles the progress portion is not shown/half hidden, so i can't see on how many chapters/episodes I am.
Might be my phone, but i don't think it was like this before.
It might be an idea to hide 'score' when not scored? It might free up space that way. 

![Screenshot_20241118-230724](https://github.com/user-attachments/assets/9268fb2c-a3f5-4095-8918-bdc5642a3444)

**Comment by rev0lgenX** [comment]
@Moonchildish Looks like your android system font size if bigger than mine. I'll resolve it in next update

**Comment by rev0lgenX** [comment]
@Moonchildish Can you create new issue in github? I will update and close it later.
