### ISSUE TITLE
Title cards on 'Grid Compact' size optimization

### ISSUE THREAD

**Issue by Moonchildish** [AniLibApp/AniLib#113]
![Screenshot_20241119-215757](https://github.com/user-attachments/assets/938cb486-d1e6-495a-bdcc-4c3742c35c30)

As shown in screenshot: longer titles will move information down, so episode/chapter counts etc. are no longer visible. 
It might be an idea to hide 'score' if title is not yet scored. 
Or something with text sizes. I will also check my phone settings.

**Comment by Moonchildish** [comment]
Changing my phone's font size helped!

But is there a way to hide the score icons and score lines? They make the title cards look less neat and also it's a bit unnecessary. It just clutter up the general look of it imo. 
I know other apps do it.
![Screenshot_20241122-124439__01](https://github.com/user-attachments/assets/b658ebb8-de20-4c50-a9c3-f7b62d26699e)

**Comment by rev0lgenX** [comment]
right now I am not planning of remove them. maybe sometime later
