### ISSUE TITLE
429 too many requests even when I'm not doing anything 

### ISSUE THREAD

**Issue by Whatsappson** [AniLibApp/AniLib#114]
## Device Information

- **Device:** Galaxy A34M 5G
- **Android Version:** Android 14
- **App Version:** 2.0.3

## Description

Error 429(too many requests) on all tabs, actions, reloads, etc on app and profile, solved on logout from my account and login again
(Detail: I didn't make too many requests, i literally just opened the app by the button on the widget)

## Screenshots (if applicable)
![Screenshot_20241212_072944_AniLib](https://github.com/user-attachments/assets/367c1b8c-6a38-48e1-97c3-d85feae11784)
![Screenshot_20241212_073007_AniLib](https://github.com/user-attachments/assets/02b11870-5133-4b5e-9c83-253d9fe448f5)
![Screenshot_20241212_073013_AniLib](https://github.com/user-attachments/assets/9ac6436f-0506-4b77-8e0f-8aeaf337c6c0)
![Screenshot_20241212_073018_AniLib](https://github.com/user-attachments/assets/607b6de7-48c3-4d3a-bd15-c0f9d1a556cd)

---

(I have some issues with the widget but I'll open another issue to explain better, thanks for this great app, i use for a long time and im a huge fan of your work, and to finish, sorry for my bad english, it isn't my native language as I'm a Brazilian,  and I'm learning english, thats because i didn't use a translator and tried to "explain me by myself")

**Comment by Whatsappson** [comment]
Hi, apologies for the delay, its happening eventually,not every time, today
i tried do make again and nothing happened.
But i dont think that I've made 90 actions on a minute, I've just opened
the app one off the times that happened the bug

Em qui., 12 de dez. de 2024, 07:55, Pushwant Rai ***@***.***>
escreveu:

**Comment by rev0lgenX** [comment]
I'll close this for now. It might be server related issue or maybe other. Please let me know if it happens again and how it came to be. 
Regards.

**Comment by Whatsappson** [comment]
Ok, thanks. I really apreciate your app

Em seg., 16 de dez. de 2024, 02:25, Pushwant Rai ***@***.***>
escreveu:
