### ISSUE TITLE
Misaligned text report

### ISSUE THREAD

**Issue by Palloxin** [AniLibApp/AniLib#23]
![immagine](https://user-images.githubusercontent.com/75091899/161514997-ccc8d190-b135-4179-b37e-400fdeab351b.png)
...
![immagine](https://user-images.githubusercontent.com/75091899/161515049-acf36958-e7b3-41b6-8d4f-5c2b30eab9d3.png)
a small aesthetic flaw, maybe you could merge "averege score"and "mean score" in this way: Average-Mean score
           0%-50%
or
Average |Mean score
0%            50%

**Comment by rev0lgenX** [comment]
I have moved score to different location since making them more compact is gonna result like that anyway. Have to think over for user overview section.

**Comment by Palloxin** [comment]
.
