### ISSUE TITLE
[Bug] Filtering a search setting a precise year will make the app give no entry as result

### ISSUE THREAD

**Issue by Palloxin** [AniLibApp/AniLib#73]
https://user-images.githubusercontent.com/75091899/203875497-4a76f0a1-62c1-49f7-8283-5c682106e835.mp4

As you can see the results of the search without a specified year are fine. If i specify tge year no results will appear

**Comment by Palloxin** [comment]
I tried witg year range and it works just fine

**Comment by Palloxin** [comment]
(to avoid github bot closing it)

**Comment by rev0lgenX** [comment]
should work now.
