### ISSUE TITLE
Change entry status with `+` button

### ISSUE THREAD

**Issue by BrutuZ** [AniLibApp/AniLib#89]
When using the `+` button to start an entry in `Plan to Watch`, it adds to the episode count and sets the start date as expected, but the status doesn't change to `Watching`, which prevents the activity posts

**Comment by Moonchildish** [comment]
I'm upping this!
I have the same problem + everytime I increment with the + it will remove my start date from list editor..
AND it doesn't add an end date whenever I finish something.
