### ISSUE TITLE
[QUESTION] New version when?

### ISSUE THREAD

**Issue by MSOB7YY** [AniLibApp/AniLib#90]
hey am a biig fan on AniLib, the app is pretty amazing and very ux friendly with good looking ui.

v1.1.19 has been there for almost a year now, i saw u been doing work on [v3 branch](https://github.com/AniLibApp/AniLib/tree/v3), is there going to be a new version or a beta soon? i tried cloning and building but things didnt go vary well.

thanks for the awesome app btw <3

**Comment by rev0lgenX** [comment]
There are lots of changes still left but it is almost complete. You can try it if you want from [here v3](https://app.bitrise.io/app/1c8e76b1ed927d8d/installable-artifacts/bcc1b67ecdb35670/public-install-page/46cab1497922d43934b1ed272137d918?utm_source=app-bitrise&utm_medium=email&utm_campaign=build-artifact-notification-mailer), it has almost all functionality, but still its not yet complete. It will soon be ready, right now there is no eta and thank you for liking my app.

**Comment by MSOB7YY** [comment]
i see, have tried it and seems awesome. best of luck for ya <3
