### ISSUE TITLE
Issue with airing section in V2

### ISSUE THREAD

**Issue by YouSummoner** [AniLibApp/AniLib#94]
In the airing section on homepage, if any filter other than the default is applied, it shows an error...
![Screenshot_20241013-210846_AniLib](https://github.com/user-attachments/assets/1fa4e1db-4d66-43fd-9ab5-6bbb2423c5c4)

By the way, really amazing work in the rewrite, now this app feels even smoother and native to new the Android. 
I've been using AniLib for the past 2 years, and looks like I'm gonna continue using it.
Really appreciate all the work you've put into it, keep it up🌟🌟🌟

**Comment by rev0lgenX** [comment]
Issue if fixed, but for now it should work after restarting the app after login and error will happen again on logout if show only planning and watching is enabled.
