### ISSUE TITLE
Minor theming improvement suggestion

### ISSUE THREAD

**Issue by YouSummoner** [AniLibApp/AniLib#95]
Not a major issue, but it would be nice if all the elements in the app could follow an amoled theme such as cards and navbar, etc. Right now, these seem to ignore the theming from android and just end up looking grey and kind of out of place compared to other apps on the device.
![Screenshot_20241013-210905_AniLib](https://github.com/user-attachments/assets/97f99de5-bcbf-4eb0-ab31-cbaa45d33916)
![Screenshot_20241013-211904_AniLib](https://github.com/user-attachments/assets/a0481a72-6449-4660-b4b0-eb970f2bac4d)

**Comment by rev0lgenX** [comment]
Hi, what theme mode did you use? I am a bit confused because I haven't added any theme with completely black background. Also, can you provide with android api version.

**Comment by YouSummoner** [comment]
Android 14 QPR3 Here
Also, the theme is custom, I also just manually made the background fully black like below.
![Screenshot_20241014-170643_AniLib](https://github.com/user-attachments/assets/4dca8fd1-e9f1-45a1-8a1a-362fd9497def)
![Screenshot_20241014-170657_AniLib](https://github.com/user-attachments/assets/bc7878b9-aef9-488f-9d7e-f00049f7ba34)

**Comment by rev0lgenX** [comment]
For custom theme- cards, navigations, app bar colors are controlled by Surface Container Low Color and Surface Container Color. I think setting that will help to change overall color. The color picker is not so great right now so, but will do it for now.

**Comment by YouSummoner** [comment]
Got it...Will try to create a nice theme with all these options. Looking forward to future updates 👍
